In [1]:
import pandas as pd
df=pd.read_csv("postings.csv")

In [7]:
df2=df.copy()

In [8]:
df2=df2[df2['job_title'].str.contains('data analyst',case=False,na=False)]

In [15]:
df2.drop(columns='job_link',inplace=True)

In [17]:
df2.count()

job_title         2752
company           2752
job_location      2752
first_seen        2752
search_city       2752
search_country    2752
job level         2752
job_type          2752
job_summary       2741
job_skills        2698
dtype: int64

In [20]:
df2=df2.dropna(subset='job_summary')

In [23]:
df2.count()

job_title         2741
company           2741
job_location      2741
first_seen        2741
search_city       2741
search_country    2741
job level         2741
job_type          2741
job_summary       2741
job_skills        2741
dtype: int64

In [22]:
df2['job_skills']=df2['job_skills'].fillna("Not Specified")

In [26]:
df2.head(3)

,job_title,company,job_location,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills
1,Volunteer: Wildfire Prevention Financing Data ...,CrowdDoing,"El Dorado Hills, CA",2023-12-20,Newcastle,United States,Associate,Onsite,Match4Action connects those wanting to volunte...,"Machine learning, Artificial intelligence, Vir..."
2,Volunteer: Biometric Data Analystat Nature Cou...,CrowdDoing,"El Dorado Hills, CA",2023-12-20,Newcastle,United States,Associate,Onsite,Match4Action connects those wanting to volunte...,"Machine learning, Artificial intelligence, Vir..."
3,"Volunteer: Medicinal Foods, Volunteer Healthca...",CrowdDoing,"El Dorado Hills, CA",2023-12-20,Newcastle,United States,Associate,Onsite,Match4Action connects those wanting to volunte...,"Machine learning, Artificial intelligence, Vir..."

In [ ]:
print(df['job_location'].sample(20, random_state=10).tolist())

['Atlanta, GA', 'London, England, United Kingdom', 'Foster City, CA', 'Columbus, OH', 'Atlanta Metropolitan Area', 'Collegeville, PA', 'Milton Keynes, England, United Kingdom', 'Olds, Alberta, Canada', 'Hull, England, United Kingdom', 'Palatka, FL', 'Riverside County, CA', 'Vaughan, Ontario, Canada', 'Austin, TX', 'Olathe, KS', 'Mason, OH', 'Houston, TX', 'Des Moines, IA', 'Pensacola, FL', 'Monroe, NJ', 'Northridge, CA']

In [34]:
df['job_location'].dropna().apply(lambda x: x.count(',')).value_counts()

job_location
1    9965
2    2322
0     606
3       1
Name: count, dtype: int64

In [54]:
print(df2['job_skills'].sample(1,random_state=1).to_list())

['SQL, Data Analytics, Digital Marketing, Data Visualization, Tableau, Power BI, Looker, Google Ads, Google Analytics, Facebook Ads Manager, Online Advertising, Web Analytics, Customer Segmentation, Campaign Tracking, Statistical Analysis, Hypothesis Testing, A/B Testing, Quantitative Methods, Python, R']

In [ ]:
def parse_location(loc):
    if pd.isna(loc):
        return pd.Series(['Unknown', 'Unknown'])
    parts = [p.strip() for p in loc.split(',')]
    if len(parts) == 1:
        # Just a country, e.g. "United States"
        return pd.Series(['Unknown', parts[0]])
    elif len(parts) == 2:
        # "City, ST" - US format
        return pd.Series([parts[0], 'United States'])
    else:
        # "City, Region, Country" - international
        return pd.Series([parts[0], parts[-1]])

df2[['city', 'country']] = df2['job_location'].apply(parse_location)

country
United States                                 2123
United Kingdom                                 294
Canada                                         181
Australia                                       80
New York City Metropolitan Area                 12
Charlotte Metro                                  6
Mexico                                           6
Atlanta Metropolitan Area                        5
Washington DC-Baltimore Area                     3
Dallas-Fort Worth Metroplex                      3
Los Angeles Metropolitan Area                    3
San Francisco Bay Area                           3
Greater St. Louis                                2
Greater Orlando                                  2
Greater Chicago Area                             2
Greater Philadelphia                             1
Greensboro--Winston-Salem--High Point Area       1
Greater Phoenix Area                             1
Raleigh-Durham-Chapel Hill Area                  1
Salt Lake City Metropolitan Area                 1
Greater Madison Area                             1
Louisville Metropolitan Area                     1
Nashville Metropolitan Area                      1
Greater Edinburgh Area                           1
Greater Seattle Area                             1
Denver Metropolitan Area                         1
Greater Leeds Area                               1
Greater Melbourne Area                           1
Greater Sacramento                               1
Greater Montreal Metropolitan Area               1
European Economic Area                           1
Name: count, dtype: int64

city
Unknown          211
London            84
New York          82
Atlanta           54
Washington        48
Chicago           48
Boston            46
Dallas            36
Austin            36
Houston           33
Los Angeles       33
Richmond          31
Charlotte         31
San Francisco     27
Miami             25
Name: count, dtype: int64

In [60]:
skills_to_check = ['python', 'sql', 'excel', 'power bi', 'tableau']

for skill in skills_to_check:
    col_name = 'has_' + skill.replace(' ', '_')
    df2[col_name] = df2['job_skills'].str.lower().str.contains(skill, na=False)

In [62]:
df2.drop(columns='job_location',inplace=True)

In [66]:
df2.reset_index(drop=True,inplace=True)

In [67]:
df2.head()

,job_title,company,first_seen,search_city,search_country,job level,job_type,job_summary,job_skills,city,country,has_python,has_sql,has_excel,has_power_bi,has_tableau
0,Data Analyst,Procession Systems,2023-12-20,Alexandria,United States,Associate,Onsite,Procession Systems is seeking a TS/SCI-Cleared...,"Data Analyst, Data Analysis, Tableau, Power BI...",Washington,United States,False,False,True,True,True
1,Data Analyst,Infinity-Outsourcing,2023-12-20,Alexandria,United States,Associate,Onsite,"Role: Data Analyst\nLocation: McLean, VA\nPay ...","Data Analysis, Sybase, DB2, ECDA, Database Req...",McLean,United States,False,False,True,False,False
2,Junior Data Analyst,Red Gate,2023-12-20,Alexandria,United States,Associate,Onsite,Company Description\nAt\nRED GATE\nwe do every...,"Data analysis, Data mining, Data visualization...",Arlington,United States,True,True,True,False,True
3,Senior Data Analyst,Accroid Inc,2023-12-20,Alexandria,United States,Associate,Onsite,12+ Months\nVA\nTechnical skills: SQL (require...,"SQL, Tableau, Python, AWS, Redshift, s3 Bucket",Reston,United States,True,True,False,False,True
4,Sr. Data Analyst,eStaffing Inc.,2023-12-20,Alexandria,United States,Associate,Onsite,"Job Title -\nSr. Data Analyst:\nWashington, DC...","SQL, Tableau, Statistical analysis, Data Analy...",Washington,United States,False,True,False,False,True

In [71]:
df2.drop(columns="country",inplace=True)

In [72]:
df2.to_csv("cleaned kaggle dataset.csv",index=False)